apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cmbu-app-frontend
  namespace: custom-application
  labels:
    app: bootcamp
spec:
  selector:
    matchLabels:
      app: bootcamp
      role: web
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: bootcamp
        role: web
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: codydearkland/cmbu-app-frontend:latest  # or just image: redis
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: custom-application
  labels:
    app: bootcamp
    role: web
    tier: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootcamp
    role: web
    tier: frontend
  type: LoadBalancer
