apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kubecon-demo
  namespace: custom-application
  labels:
    app: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
      role: web
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: demoapp
        role: web
        tier: frontend
    spec:
      containers:
      - name: demoapp
        image: codydearkland/csdemoapp:latest  # or just image: redis
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: custom-application
  labels:
    app: demoapp
    role: web
    tier: frontend
  name: kubecon-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
    role: web
    tier: frontend
  type: LoadBalancer
