version: 2.1

orbs:
    docker: circleci/docker@0.1.0
    vmwarecs: vmwarecs/code-stream@dev:first

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: codydearkland/$CIRCLE_PROJECT_REPONAME
  call-pipeline:
    jobs:
      - vmwarecs/call-pipeline:
          refresh_token: ${refresh_token}