version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:latest

orbs:
    docker: circleci/docker@0.1.0
    vmwarecs: vmwarecs/code-stream@dev:first


workflows:
  Build-Docker-Image-Push-Call-Code-Stream:
    jobs:
      - docker/publish:
          image: codydearkland/$CIRCLE_PROJECT_REPONAME
      - vmwarecs/callcs:
            requires: 
                - docker/publish
            csp_token: CSP_REFRESH_TOKEN
            pipeline_id: PIPELINE_ID

