version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:latest


orbs:
    docker: circleci/docker@0.1.0
    vmwarecs: vmwarecs/code-stream@dev:first


workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: codydearkland/$CIRCLE_PROJECT_REPONAME

  call-code-stream:
    jobs:
      - vmwarecs/callcs